# Algorithme du pivot de Gauss

Dans ce TP et le suivant, vous allez progressivement mettre en place l'algorithme de Gauss permettant de résoudre des systèmes linéaires.

** ATTENTION : **

+ ** Les signatures de vos fonctions doivent être strictement identiques, casse incluse, à celles de l'énoncé. **
+ ** Certains éléments de ce TP seront à rendre sur Moodle. **
+ ** Si la signature n'est pas respectée, votre fonction échouera aux tests. **
+ ** Dans le test Moodle, vous ne devez déposer que votre fonction (les imports seront faits, surtout pas de print, ni de test) **

## Fonction d'échange de lignes

Ecrivez une fonction `Echange(i,j,A)` qui retourne la matrice A dans laquelle les lignes $i$ et $j$ ont été échangées.

Par exemple :

+ Avec $A = \left(\begin{matrix} 
1 & -3 & 2 \\
2 & 4 & -1 \\
5 & 11 & 3
\end{matrix}\right)$, l'appel de `Echange(1,2,A)` doit retourner :
$\left(\begin{matrix} 
1 & -3 & 2 \\
5 & 11 & 3 \\
2 & 4 & -1 \\
\end{matrix}\right)$

+ Avec $B = \left(\begin{matrix} 
0 & 7 & -1 & 6 & 7 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
2 & 8 & 6 & -4 & 2 \\
\end{matrix}\right)$, l'appel de `Echange(0,3,B)` doit retourner :
$\left(\begin{matrix} 
2 & 8 & 6 & -4 & 2 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
0 & 7 & -1 & 6 & 7 \\
\end{matrix}\right)$

** En Python, la matrice `A` doit être un `numpy.array`; `i` et `j` sont des entiers **

In [1]:
# Exécutez cette cellule pour importer numpy.
# Cet import est valable "une fois pour toute", vous pouvez utiliser numpy dans les autres cellules.
import numpy as np
def test(a:int, b:int=2):
    print(a+b)
test(3)

5


In [3]:
# Insérez et testez le code de votre fonction `Echange` ici
#Retourne la matrice A dans laquelle les lignes 𝑖 et 𝑗 ont été échangées.
def Echange(i, j , A):
    M = np.copy(A)
    M[i,:] = A[j,:]
    M[j,:] = A[i,:]
    return M

#Retourne la matrice A dans laquelle à la ligne 𝑖 a été ajoutée 𝑙 fois la ligne 𝑗.
def CombinaisonLineaire(i, l, j , A):
    M = np.copy(A)
    M[i,:] = A[i,:] + l*A[j,:]
    return M

#Compris
def ChoixPivot(j,A):
    nbLignes = A.shape[0]
    i = j;
    while (i < nbLignes and A[i,j]==0):
        i = i + 1
    if (i == nbLignes):
        i=-1
    return i

def Echelonne(A):
    nbLignes, nbColonnes = A.shape
    for j in range(nbColonnes-2):
        pivot = ChoixPivot(j,A)
        if j != pivot:
            A = Echange(pivot,j,A)
        for i in range (j+1,nbLignes):
            A = CombinaisonLineaire(i, -A[i,j]/A[pivot,j], pivot , A)
    return A

def Gauss(A):
    A = Echelonne(A)
    nbLignes, nbColonnes = A.shape
    for i in reversed(range(nbLignes)):
        for n in range (i+1, nbColonnes-1):
            A[i,-1] = A[i,-1] - A[i,n]
            A[i,n] = 0
        A[i,-1] = A[i,-1]/A[i,i]
        A[i,i] = 1
        for n in reversed(range(i)):
            A[n,i] = A[n,i]*A[i,-1]
    res = A[:,-1]
    res.shape = nbLignes
    return res


mat = np.array([[1, 1, 1, 1], [2, 1, -1, -2], [-1, 1, -2, -7]])
print(Echelonne(mat))
print(Gauss(mat))

[[  1   1   1   1]
 [  0  -1  -3  -4]
 [  0   0  -7 -14]]
[ 1 -2  2]


## Fonction de combinaison linéaire

Ecrivez une fonction `CombinaisonLineaire(i,l,j,A)` qui retourne la matrice A dans laquelle à la ligne $i$ a été ajoutée $l$ fois la ligne $j$.

Par exemple :

+ Avec $A = \left(\begin{matrix} 
1 & -3 & 2 \\
2 & 4 & -1 \\
5 & 11 & 3
\end{matrix}\right)$, l'appel de `CombinaisonLineaire(0,-5,1,A)` doit retourner :
$\left(\begin{matrix} 
-9 & -23 & 7 \\
2 & 4 & -1 \\
5 & 11 & 3
\end{matrix}\right)$

+ Avec $B = \left(\begin{matrix} 
0 & 7 & -1 & 6 & 7 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
2 & 8 & 6 & -4 & 2 \\
\end{matrix}\right)$, l'appel de `CombinaisonLineaire(3,-2,2,A)` doit retourner :
$\left(\begin{matrix} 
0 & 7 & -1 & 6 & 7 \\
4 & 8 & 5 & -1 & 0 \\
1 & 5 & -9 & 3 & -5 \\
0 & -2 & 24 & -10 & 12 \\
\end{matrix}\right)$

** En Python, le coefficient `l` est un nombre réel **

In [9]:
# Insérez et testez le code de votre fonction `CombinaisonLineaire` ici
A = np.array([[2, 1], [-1, 3], [4, -1]])

print (A @ np.transpose(A))
print (np.transpose(A) @ A)



[[ 5  1  7]
 [ 1 10 -7]
 [ 7 -7 17]]
[[21 -5]
 [-5 11]]


## Fonction de choix du pivot

** Attention : ** Cette fonction est un peu plus difficile. Lisez attentivement l'énoncé. Demandez à votre enseignant !

La fonction `ChoixPivot(j,A)` doit retourner, en cherchant dans la colonne $j$, le premier indice de ligne $i$ sous la diagonale (diagonale incluse) tel que $A_{i,j} \not= 0$. Si un tel coefficient n'existe pas, la fonction retourne $-1$.

Par exemple avec la matrice :
$$A = \left(\begin{matrix}
0 & 1 & 2 & 3 \\
0 & 2 & 1 & 5 \\
1 & 0 & 0 & 4 \\
2 & 7 & 0 & 8 \\
\end{matrix}\right)$$

+ `ChoixPivot(0,A)` retourne $2$
+ `ChoixPivot(1,A)` retourne $1$ : Le coefficient sur la diagonale est non-nul
+ `ChoixPivot(2,A)` retourne $-1$ : Il n'y a pas de coefficient non-nul sous la diagonale dans cette colonne
+ `ChoixPivot(3,A)` retourne $3$

In [2]:
# Insérez et testez le code de votre fonction `ChoixPivot` ici

# Fin !