# Analyse de Données - Développeur
## TP1 : Tableaux de Données et Espaces
### 1) Après avoir téléchargé le fichier "td1.text", exécutez le code ci-dessous.

In [22]:
import numpy as np
X = np.loadtxt("td1.txt")
print("X =\n",X)

X =
 [[ 3. -1.]
 [-1.  2.]
 [ 4.  2.]]


### 2) Affectez les dimensions du tableau à deux variables $n$ et $p$.

In [23]:
np.shape (X) #La propriété shape du tableau X

#Pour les affecter à deux variables n et p
n, p = X.shape
print("il y'a ",n," individus et ",p," variables.")
n, p

il y'a  3  individus et  2  variables.


(3, 2)

### 3) Trouvez le moyen de centrer le tableau. Vous noterez $Xp$ le tableau résultat. 

In [25]:
#xbar = np.mean(X) #Ne fonctionne pas car il prend le tableau en entier, il faut lui donner la "tranche"
#xbar


#------------ Correction ------------
# xbar = np.mean (X,axis=0) #On précise l'axe
# Xbar représente le centre du tableau
Xbar = X.mean(axis=0)

print("La moyenne (et le centre) du tableau est ",Xbar)
#On soustrait donc Xbar à notre tableau X pour centrer le tableau en 0
Xp = X - Xbar
print("Le tableau centré en 0 donne donc :\n",Xp)

La moyenne du tableau est  [2. 1.]
Le tableau centré donne donc:
 [[ 1. -2.]
 [-3.  1.]
 [ 2.  1.]]


### 4) Créez la métrique $D_n$ de l'espace des variables à partir de la matrice Identité.

In [27]:
#Matrice identité à l'aide de la fonction eye
#np.eye(3)
#array([[ 1.,  0.,  0.],
       #[ 0.,  1.,  0.],
       #[ 0.,  0.,  1.]])

#------------ Correction ------------
Dn = np.eye(n) / n
Dn #Affichage de Dn

array([[0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333]])

### 5) Calculez la $D_n$-norme de la 2ème variable par produit scalaire. 

In [33]:
#Récupérer la deuxième colonne du tableau X'
#C'est un tableau 2 dimensions
Xp2 = Xp[:,1]  #On choisis toutes les lignes ":" et la colonne 1
Xp2

# .dot sert à faire le produit scalaire.
# La multication est un produit scalaire particulier
# donc, .dot sert entre autre à multiplier
# .dot peut aussi s'écrire @

#np.dot(X2.T,np.dot(Dn,X2))

# solution 1
Xp2.T.dot(Dn).dot(Xp2)

# solution 2
#Xp2.T @ Dn @ Xp2

1.9999999999999998

### 6) Généralisez par produit matriciel. Vous noterez *V* résultat.

In [34]:
#Pour généraliser par produit matriciel (.dot, @, produit scalaire) on fait le produit de
#    notre tableau transposé centré (Xp)
#    de la métique Dn
#    du tableau Xp
v = Xp.T @ Dn @ Xp
v

array([[ 4.66666667, -1.        ],
       [-1.        ,  2.        ]])

### 7) Trouvez le moyen de contruire le tableau centré-réduit que vous noterez *Xs*. 

In [35]:
#Le tableau Xs va être centré réduit en divisant le tab centré Xp par le tableau X à l'axe 0
Xs = Xp / X.std(axis=0)
#.std (pour standart) permet de faire l'écart type sur Xs
Xs.std(axis=0)

#Autre solution - calcul des D normes
#Xs.T@D@Xa

array([1., 1.])

### 8) Reprenez la généralisation (question 6) sur le tableau *Xs*. Qu'obtient-on ? 

In [36]:
vs = Xs.T @ Dn @ Xs
vs


array([[ 1.        , -0.32732684],
       [-0.32732684,  1.        ]])

### 9) A l'aide de fonctions *numpy* et/ou méthodes de *nd-arrays*, retrouvez le centre du nuage, les matrices de covariance et de corrélations des données. 

In [37]:
#centre du nuage
X1bar = X.sum(axis = 0) / n 
print("Le centre du nuage se trouve au point de coordonnée ",X1bar)

#matrice de covariance
print("La matrice de covariance est \n", np.cov(X))

#corrélation des données
print("Le tableau de corrélation des données est\n",np.corrcoef(X))

Le centre du nuage se trouve au point de coordonnée  [2. 1.]
La matrice de covariance est 
 [[ 8.  -6.   4. ]
 [-6.   4.5 -3. ]
 [ 4.  -3.   2. ]]
Le tableau de corrélation des données est
 [[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]


### 10) Ecrivez une fonction (que vous testerez sur $X$) permettant de 
#### - centrer et optionnellement réduire un tableau *data*
#### - retourner les données transformées et la matrice de covariance de celles-ci

In [39]:
def standardize(data,scale=False):
    # centrer
    dataBar = data.mean(axis=0)
    dataP = data - dataBar
    # réduire
    dataS = dataP / data.std(axis=0)
    return dataS.std(axis=0)

standardize(X)
#A FAIRE POUR LE TD PROCHAIN

array([1., 1.])

In [33]:
#Xp V = standardise(X)
Xs, R = (X, True)