# Analyse de Données - Développeur
## TP1 : Tableaux de Données et Espaces
### 1) Après avoir téléchargé le fichier "td1.text", exécutez le code ci-dessous.

In [1]:
import numpy as np
X = np.loadtxt("td1.txt")
print("X =\n",X)

X =
 [[ 3. -1.]
 [-1.  2.]
 [ 4.  2.]]


### 2) Affectez les dimensions du tableau à deux variables $n$ et $p$.

In [2]:
np.shape(X)
n, p = X.shape
print("il y'a ",n," individus et ",p," variables.")
n, p

il y'a  3  individus et  2  variables.


(3, 2)

### 3) Trouvez le moyen de centrer le tableau. Vous noterez $Xp$ le tableau résultat. 

In [3]:
#Pour centrer le tableau on va créer une variable Xbar qui nous donnera la moyenne du tableau à l'axe 0 et on soustraira à Xbar le tableau X pour centrer le tableau
Xbar = X.mean(axis = 0)
print("La moyenne du tableau est ",Xbar)
#On soustrait donc Xbar à notre tableau X pour centrer le tableau
Xp = X - Xbar
print("Le tableau centré donne donc:\n",Xp)


La moyenne du tableau est  [2. 1.]
Le tableau centré donne donc:
 [[ 1. -2.]
 [-3.  1.]
 [ 2.  1.]]


### 4) Créez la métrique $D_n$ de l'espace des variables à partir de la matrice Identité.

In [4]:
#Pour créer la métrique Dn on utilise np.identity et on met en param le nombre d'individus 
Dn = np.identity(3) / n
Dn

array([[0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333]])

### 5) Calculez la $D_n$-norme de la 2ème variable par produit scalaire. 

In [10]:
#Xp2 c'est juste les éléments de la 2eme variable c'est pour ça qu'on met [:,1] 1 est correspond à la rangée de la 2ème variable
XbarX = X.mean(axis = 0)/3
Xp2 = Xp[:,1]
#.dot nous sert à faire le produit entre le tableau transposée de Xp2 et Dn et Xp2
#On peut utiliser @ en tant que raccourci de .dot
Xp2.T.dot(Dn).dot(Xp2)
Xp2.T @ Dn @ Xp2





1.9999999999999998

### 6) Généralisez par produit matriciel. Vous noterez *V* résultat.

In [37]:
#Pour généraliser par produit matriciel on fait le produit de notre tableau transposé centré (Xp) de la métique Dn et du tableau Xp
V =  Xp.T.dot(Dn).dot(Xp)
V 

array([[ 4.66666667, -1.        ],
       [-1.        ,  2.        ]])

### 7) Trouvez le moyen de contruire le tableau centré-réduit que vous noterez *Xs*. 

In [59]:
#Le tableau Xs va être centré réduit en divisant le tab centré Xp par le tableau X à l'axe 0
Xs = Xp / X.std(axis = 0)
#.std permet de faire l'écart type sur Xs
Xs.std(axis=0)


array([1., 1.])

### 8) Reprenez la généralisation (question 6) sur le tableau *Xs*. Qu'obtient-on ? 

In [60]:
Xs_g = Xs.T @ Dn @ Xp
Xs_g

array([[ 2.1602469 , -0.46291005],
       [-0.70710678,  1.41421356]])

### 9) A l'aide de fonctions *numpy* et/ou méthodes de *nd-arrays*, retrouvez le centre du nuage, les matrices de covariance et de corrélations des données. 

In [72]:
#centre du nuage
X1bar = X.sum(axis = 0) / n 
print("Le centre du nuage se trouve au point de coordonnée ",X1bar)

#matrice de covariance
print("La matrice de covariance est \n", np.cov(X))

#corrélation des données
print("Le tableau de corrélation des données est\n",np.corrcoef(X))


Le centre du nuage se trouve au point de coordonnée  [2. 1.]
La matrice de covariance est 
 [[ 8.  -6.   4. ]
 [-6.   4.5 -3. ]
 [ 4.  -3.   2. ]]
Le tableau de corrélation des données est
 [[ 1. -1.  1.]
 [-1.  1. -1.]
 [ 1. -1.  1.]]


### 10) Ecrivez une fonction (que vous testerez sur $X$) permettant de 
#### - centrer et optionnellement réduire un tableau *data*
#### - retourner les données transformées et la matrice de covariance de celles-ci

In [84]:
def standardize(data,scale=False):
    Xbar = data.mean(axis=0)
    Xp = data - Xbar
    
    return "Tableau centré: ",Xp,"La matrice de covariance: ",np.cov(X)

standardize(X,scale=False)


('Tableau centré: ',
 array([[ 1., -2.],
        [-3.,  1.],
        [ 2.,  1.]]),
 'La matrice de covariance: ',
 array([[ 8. , -6. ,  4. ],
        [-6. ,  4.5, -3. ],
        [ 4. , -3. ,  2. ]]))